version: '3.7'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: enneagram
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data:
